# Dockerfile.frontend
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY frontend ./frontend

ENV PYTHONUNBUFFERED=1
ENV BACKEND_URL="http://backend:8000"

EXPOSE 8501

WORKDIR /app/frontend
CMD ["streamlit", "run", "app.py", "--server.address", "0.0.0.0", "--server.port", "8501"]
